package gingermathgame;


import java.awt.Color;
import java.awt.Font;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Corvette
 */
public class MainMenu extends javax.swing.JFrame{
    
    private Socket socket;
    private BufferedReader in;
    private PrintWriter out;
    private PlayerInformation playerInfo;
    private SettingInformation setting;
    private boolean soundChk = true;

    
    public MainMenu() {
        initComponents();

        setLocationRelativeTo(null);
        setSize(854, 480);
        jPanel1.setBackground(new Color(0, 0, 0, 0));
        jPanel2.setBackground(new Color(0, 0, 0, 0));
        jPanel3.setBackground(new Color(0, 0, 0, 0));
        jPanel4.setBackground(new Color(0, 0, 0, 0));
        jPanel5.setBackground(new Color(0, 0, 0, 0));
        buttonPanel.setBackground(new Color(0, 0, 0, 0));
        
        //#SOUND
        setting = new SettingInformation();
        setting.loadSetting();
        
        //#profileInfo
        
    }
    
    public void setSocket(Socket socket, BufferedReader in, PrintWriter out){
        System.out.println("Main menu set socket.");
        this.socket = socket;
        this.in = in;
        this.out = out;
    }
    
    public void loadPlayerInformation(){
        playerInfo = new PlayerInformation();
        if(playerInfo.loadInformation()){
            out.println("oldname " + playerInfo.getName());
            profileInfo.setText(playerInfo.getName());
        }else{
            while(true){
                try {
                    String createPlayerName = (String)JOptionPane.showInputDialog(null, "player name : ", "Create new player", JOptionPane.PLAIN_MESSAGE, null, null, "name");
                    out.println("name " + createPlayerName);
                    String feedback = in.readLine();
                    if(feedback.equals("acc")){
                        playerInfo.setName(createPlayerName);
                        playerInfo.saveInfo();
                        profileInfo.setText(playerInfo.getName());
                        JOptionPane.showMessageDialog(null, "Done");
                        break;
                    }else if(feedback.equals("dup")){
                        JOptionPane.showMessageDialog(null, "name duplicate","Create player name",JOptionPane.WARNING_MESSAGE);
                    }
                } catch (IOException ex) {
                    Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
                }
            } 
        }
    }
    
    // #SOUND for loading presetting propose
    public void loadSetting(){
        setting = new SettingInformation();
        if(setting.loadSetting()){
            if(setting.getS().equals("OFF")){
                soundChk = false;
            }else{
                soundChk = true;
            }
        }
    }
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        jPanel4 = new javax.swing.JPanel();
        gradientPanel1 = new gingermathgame.GradientPanel();
        jPanel1 = new javax.swing.JPanel();
        welcomeText = new javax.swing.JLabel();
        profileInfo = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        labelName = new javax.swing.JLabel();
        buttonPanel = new javax.swing.JPanel();
        buttonQuick = new javax.swing.JButton();
        buttonMultiplayer = new javax.swing.JButton();
        buttonSett = new javax.swing.JButton();
        buttonExit = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 91, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });

        welcomeText.setFont(new java.awt.Font("Kanit", 2, 24)); // NOI18N
        welcomeText.setForeground(new java.awt.Color(255, 255, 255));
        welcomeText.setText("Welcome");

        profileInfo.setBackground(new java.awt.Color(138, 192, 84));
        profileInfo.setFont(new java.awt.Font("Kanit", 0, 18)); // NOI18N
        profileInfo.setForeground(new java.awt.Color(255, 255, 255));
        profileInfo.setContentAreaFilled(false);
        profileInfo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        profileInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileInfoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(welcomeText, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(profileInfo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(welcomeText, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(profileInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 151, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        labelName.setFont(new java.awt.Font("Sweet Sensations Personal Use", 0, 64)); // NOI18N
        labelName.setForeground(new java.awt.Color(255, 255, 255));
        labelName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelName.setText(" Ginger Math ");

        buttonQuick.setBackground(new java.awt.Color(138, 192, 84));
        buttonQuick.setFont(new java.awt.Font("Kanit", 2, 16)); // NOI18N
        buttonQuick.setForeground(new java.awt.Color(255, 255, 255));
        buttonQuick.setText(" Quick Play ");
        buttonQuick.setBorder(null);
        buttonQuick.setBorderPainted(false);
        buttonQuick.setFocusPainted(false);
        buttonQuick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonQuickActionPerformed(evt);
            }
        });

        buttonMultiplayer.setBackground(new java.awt.Color(75, 137, 218));
        buttonMultiplayer.setFont(new java.awt.Font("Kanit", 2, 16)); // NOI18N
        buttonMultiplayer.setForeground(new java.awt.Color(255, 255, 255));
        buttonMultiplayer.setText(" Multiplayer ");
        buttonMultiplayer.setBorder(null);
        buttonMultiplayer.setBorderPainted(false);
        buttonMultiplayer.setFocusPainted(false);
        buttonMultiplayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMultiplayerActionPerformed(evt);
            }
        });

        buttonSett.setBackground(new java.awt.Color(159, 99, 165));
        buttonSett.setFont(new java.awt.Font("Kanit", 2, 16)); // NOI18N
        buttonSett.setForeground(new java.awt.Color(255, 255, 255));
        buttonSett.setText(" Setting ");
        buttonSett.setBorder(null);
        buttonSett.setBorderPainted(false);
        buttonSett.setFocusPainted(false);
        buttonSett.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSettActionPerformed(evt);
            }
        });

        buttonExit.setBackground(new java.awt.Color(100, 108, 119));
        buttonExit.setFont(new java.awt.Font("Kanit", 2, 16)); // NOI18N
        buttonExit.setForeground(new java.awt.Color(255, 255, 255));
        buttonExit.setText(" Exit ");
        buttonExit.setBorder(null);
        buttonExit.setBorderPainted(false);
        buttonExit.setFocusPainted(false);
        buttonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttonPanelLayout = new javax.swing.GroupLayout(buttonPanel);
        buttonPanel.setLayout(buttonPanelLayout);
        buttonPanelLayout.setHorizontalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buttonQuick, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(buttonMultiplayer, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
            .addComponent(buttonSett, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(buttonExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        buttonPanelLayout.setVerticalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addComponent(buttonQuick, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(buttonMultiplayer, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(buttonSett, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(buttonExit, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout gradientPanel1Layout = new javax.swing.GroupLayout(gradientPanel1);
        gradientPanel1.setLayout(gradientPanel1Layout);
        gradientPanel1Layout.setHorizontalGroup(
            gradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gradientPanel1Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(gradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gradientPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(labelName, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE))
                    .addGroup(gradientPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(29, 29, 29)
                        .addComponent(buttonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(20, 20, 20)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        gradientPanel1Layout.setVerticalGroup(
            gradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(gradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelName, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                .addGap(35, 35, 35)
                .addGroup(gradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(124, 124, 124))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized

        double component = getWidth()*getHeight();
        double current = 854*480;
    
        buttonSett.setFont(new Font(buttonSett.getFont().getName(), buttonSett.getFont().getStyle(), (int)(16*(component/current))));
        buttonQuick.setFont(new Font(buttonQuick.getFont().getName(), buttonQuick.getFont().getStyle(), (int)(16*(component/current))));
        buttonMultiplayer.setFont(new Font(buttonMultiplayer.getFont().getName(), buttonMultiplayer.getFont().getStyle(), (int)(16*(component/current))));
        buttonExit.setFont(new Font(buttonExit.getFont().getName(), buttonExit.getFont().getStyle(), (int)(16*(component/current))));
        labelName.setFont(new Font(labelName.getFont().getName(), labelName.getFont().getStyle(), (int)(64*(component/current))));
//        welcomeText.setFont(new Font(welcomeText.getFont().getName(), welcomeText.getFont().getStyle(), (int)(24*(component/current))));
//        profileInfo.setFont(new Font(welcomeText.getFont().getName(), welcomeText.getFont().getStyle(), (int)(18*(component/current))));
        
    }//GEN-LAST:event_formComponentResized

    private void buttonSettActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSettActionPerformed
        SoundControl.playSound("click.wav");
        loadSetting();
        SettingDialog settingDialog = new SettingDialog(this, true, soundChk);
        String[] result = settingDialog.run();
        if(result != null){
            int width = Integer.parseInt(result[0]);
            int height = Integer.parseInt(result[1]);
            setSize(width, height);
            setLocationRelativeTo(null);
        }
        
        
    }//GEN-LAST:event_buttonSettActionPerformed

    private void buttonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExitActionPerformed
        SoundControl.playSound("click.wav");
        System.exit(0);
    }//GEN-LAST:event_buttonExitActionPerformed

    private void buttonQuickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonQuickActionPerformed
        SoundControl.playSound("click.wav");
        GameImplement game = new GameImplement();
        game.setPlayerInfo(playerInfo);
        GamePlayScreen gameGUI = new GamePlayScreen(game);
        setAlwaysOnTop(true);
        gameGUI.setSize(getSize());
        gameGUI.setLocationRelativeTo(this);
        gameGUI.setVisible(true);
        dispose();
    }//GEN-LAST:event_buttonQuickActionPerformed

    private void buttonMultiplayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMultiplayerActionPerformed
        SoundControl.playSound("click.wav");
        Lobby lobby = new Lobby();
        lobby.setName(playerInfo.getName());
        lobby.setSocket(socket, in, out);
        lobby.setListRoom();
        setAlwaysOnTop(true);
        lobby.setSize(getSize());
        lobby.setLocationRelativeTo(this);
        lobby.setVisible(true);
        dispose();
    }//GEN-LAST:event_buttonMultiplayerActionPerformed

    private void profileInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileInfoActionPerformed
        Profile pf = new Profile(playerInfo, this);
        int score = playerInfo.getScore();
        out.println("upr "+ playerInfo.getName() + "-" + score);
        out.println("rqr -");
        try {
            String[] s = in.readLine().split(" ");
            int rank = Integer.parseInt(s[1])+1;
            pf.setRanking(rank);
            pf.setSize(getSize());
            pf.setLocationRelativeTo(this);
            pf.setAlwaysOnTop(true);
            pf.setVisible(true);
            setVisible(false);
        } catch (IOException ex) {
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
    }//GEN-LAST:event_profileInfoActionPerformed
       
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonExit;
    private javax.swing.JButton buttonMultiplayer;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton buttonQuick;
    private javax.swing.JButton buttonSett;
    private gingermathgame.GradientPanel gradientPanel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JLabel labelName;
    private javax.swing.JButton profileInfo;
    private javax.swing.JLabel welcomeText;
    // End of variables declaration//GEN-END:variables

   
}
